import { type Product } from '@/lib/merchant-engine';

export { type Product };

export const MUXINTANG_CATEGORIES = [
  { id: 'all', name: '全部' },
  { id: '牧心吉品', name: '牧心吉品' },
  { id: '爱宠配饰', name: '爱宠配饰' },
  { id: '数字法物', name: '数字法物' },
  { id: '密法读物', name: '密法读物' },
];

export const MOCK_DATA: Product[] = [
  {
    id: 'prod-muxin-001',
    tenant_id: 'muxintang',
    name: '开光五帝钱 · 旺财化煞',
    description: '精选古法仿制五帝铜钱，牧心堂阿阇梨净手加持，挂于门楣，旺家运、挡煞气。',
    price: 168.00,
    image: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=Chinese%20five%20emperor%20coins%20fengshui%20amulet%20red%20string%20traditional&image_size=portrait_4_3',
    category: '牧心吉品',
    tags: ['五帝钱', '旺财', '化煞'],
    stock: 100,
    is_active: true,
    sort_order: 1,
    created_at: '2026-07-21T00:00:00Z',
  },
  {
    id: 'prod-muxin-002',
    tenant_id: 'muxintang',
    name: '手工编绳 · 平安护身符',
    description: '红绳搭配金刚结，内含阿阇梨手写祈福纸卷，贴身佩戴，祈愿平安。',
    price: 88.00,
    image: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=Handmade%20red%20string%20amulet%20bracelet%20Chinese%20lucky%20charm%20protection&image_size=portrait_4_3',
    category: '牧心吉品',
    tags: ['红绳', '护身符', '平安'],
    stock: 150,
    is_active: true,
    sort_order: 2,
    created_at: '2026-07-21T00:00:00Z',
  },
  {
    id: 'prod-muxin-003',
    tenant_id: 'muxintang',
    name: '檀木法器 · 六字真言手串',
    description: '老山檀香木串，每颗珠子皆刻有六字真言，持之清净，安神定心。',
    price: 128.00,
    image: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=Sandalwood%20bead%20bracelet%20six%20word%20mantra%20carved%20Tibetan%20style&image_size=portrait_4_3',
    category: '牧心吉品',
    tags: ['檀木', '六字真言', '手串'],
    stock: 50,
    is_active: true,
    sort_order: 3,
    created_at: '2026-07-21T00:00:00Z',
  },
  {
    id: 'prod-muxin-004',
    tenant_id: 'muxintang',
    name: '宠物福缘铃铛挂饰',
    description: '铜制小铃铛，音色清脆，挂于爱宠颈间，灵兽相伴，福缘自来。',
    price: 49.00,
    image: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=Pet%20bell%20charm%20copper%20traditional%20Chinese%20style%20cute%20design&image_size=portrait_4_3',
    category: '爱宠配饰',
    tags: ['宠物', '铃铛', '福缘'],
    stock: 200,
    is_active: true,
    sort_order: 4,
    created_at: '2026-07-21T00:00:00Z',
  },
  {
    id: 'prod-muxin-005',
    tenant_id: 'muxintang',
    name: '爱宠平安项圈',
    description: '手工编织项圈，内置微缩祈福经文，愿爱宠无病无灾，安康快乐。',
    price: 88.00,
    image: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=Handmade%20pet%20collar%20with%20blessing%20scripture%20peaceful%20design&image_size=portrait_4_3',
    category: '爱宠配饰',
    tags: ['宠物', '项圈', '平安'],
    stock: 100,
    is_active: true,
    sort_order: 5,
    created_at: '2026-07-21T00:00:00Z',
  },
  {
    id: 'prod-muxin-006',
    tenant_id: 'muxintang',
    name: '数字开光符 · 电子壁纸',
    description: '牧心堂专属AI生成符箓壁纸，带有阿阇梨加持能量，可下载至手机屏保，护持正念。',
    price: 19.90,
    image: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=Digital%20talisman%20wallpaper%20Chinese%20traditional%20fu%20symbol%20AI%20art&image_size=portrait_4_3',
    category: '数字法物',
    tags: ['数字符', '壁纸', '加持'],
    stock: -1,
    is_active: true,
    sort_order: 6,
    created_at: '2026-07-21T00:00:00Z',
  },
  {
    id: 'prod-muxin-007',
    tenant_id: 'muxintang',
    name: '静心梵音 · 白噪音疗愈音频',
    description: '阿阇梨诵念的舒缓白噪音音频，适合日常静心、睡眠辅助。',
    price: 39.90,
    image: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=Meditation%20sound%20healing%20audio%20cover%20zen%20peaceful%20minimalist&image_size=portrait_4_3',
    category: '数字法物',
    tags: ['梵音', '白噪音', '疗愈'],
    stock: -1,
    is_active: true,
    sort_order: 7,
    created_at: '2026-07-21T00:00:00Z',
  },
  {
    id: 'prod-muxin-008',
    tenant_id: 'muxintang',
    name: '《牧心堂随笔》电子版',
    description: '任书颖阿阇梨日常修行随笔集，涵盖唐密实修、空间能量感悟。',
    price: 29.90,
    image: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=Chinese%20spiritual%20essay%20book%20cover%20traditional%20style%20elegant&image_size=portrait_4_3',
    category: '密法读物',
    tags: ['随笔', '唐密', '修行'],
    stock: -1,
    is_active: true,
    sort_order: 8,
    created_at: '2026-07-21T00:00:00Z',
  },
  {
    id: 'prod-muxin-009',
    tenant_id: 'muxintang',
    name: '唐密心经 · 简体注音本',
    description: '《般若波罗蜜多心经》简体注音与白话解读，适合初入唐密者阅读。',
    price: 19.90,
    image: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=Heart%20Sutra%20book%20cover%20Buddhist%20scripture%20Chinese%20traditional&image_size=portrait_4_3',
    category: '密法读物',
    tags: ['心经', '注音', '唐密'],
    stock: -1,
    is_active: true,
    sort_order: 9,
    created_at: '2026-07-21T00:00:00Z',
  },
];
